server:
  port: 8080 #项目启动端口号
  servlet:
    context-path: / #访问前缀路径
#spring:
#  datasource: #mysql数据库连接配置
#    username: root
#    password: root123456
#    url: jdbc:mysql://localhost:3306/spring4_demo03?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus: #mybatis日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
#          url: jdbc:mysql://localhost:3306/spring4_demo03?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          username: root
          password: root123456
        #          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        slave_1:
          url: jdbc:mysql://localhost:3306/spring4_demo03?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          username: root
          password: root123456
        #          driver-class-name: com.mysql.jdbc.Driver
        slave_2:
          url: jdbc:mysql://localhost:3306/spring4_demo03_tx?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          username: root
          password: root123456
        slave_3:
          url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          username: root
          password: root123456

        #        slave_3:
        #          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
        #          username: ENC(xxxxx)
        #          password: ENC(xxxxx)
        #          driver-class-name: com.mysql.jdbc.Driver

        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2
mybatis-plus: #mybatis日志，注意不要有空格，否则可能无法打印sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印

